version: '3.9'

services:
  db:
    image: postgres:15.0-alpine
    #command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    restart: always
    networks:
        - barbershop-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresAdmin!
      POSTGRES_DB: postgres
      SECRET_KEY: segredin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  barbershop-backend:
    image: barbershop-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
        - barbershop-network
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DATABASE: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SECRET_KEY: ${SECRET_KEY}
networks:
  barbershop-network:
    driver: bridge
    external: true
volumes:
    postgres_data:
      driver: local