server:
  port: 8080
spring:
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  config:
    name: barbershop
    jwt:
      secret: secret
      expiration: 86400000
  datasource:
    #url: jdbc:postgresql://db:5432/postgres?currentSchema=barbershop_db
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=barbershop_db
    username: ""
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: barbershop_db
        jdbc:
          time_zone: UTC
spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
