CREATE SCHEMA IF NOT EXISTS BARBERSHOP_DB;

CREATE TABLE IF NOT EXISTS BARBERSHOP_DB.users
(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  email    VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS BARBERSHOP_DB.salons
(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BARBERSHOP_DB.barbers
(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  is_available BOOLEAN NOT NULL,
  salon_id BIGINT,
  FOREIGN KEY (salon_id) REFERENCES BARBERSHOP_DB.salons(id)
);

CREATE TABLE IF NOT EXISTS BARBERSHOP_DB.barber_services
(
  barber_id BIGINT NOT NULL,
  service VARCHAR(255),
  FOREIGN KEY (barber_id) REFERENCES BARBERSHOP_DB.barbers(id)
);

CREATE TABLE IF NOT EXISTS BARBERSHOP_DB.reservations
(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  customer VARCHAR(255) NOT NULL,
  time TIMESTAMP NOT NULL,
  salon_id BIGINT,
  barber_id BIGINT,
  FOREIGN KEY (salon_id) REFERENCES BARBERSHOP_DB.salons(id),
  FOREIGN KEY (barber_id) REFERENCES BARBERSHOP_DB.barbers(id)
);

INSERT INTO BARBERSHOP_DB.users (username, password, email)VALUES ('teste', 'teste', 'teste@gmail.com');

SELECT * FROM BARBERSHOP_DB.users;